services:
  db:
    container_name: koloda_db
    image: localhost/koloda_db:latest
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: bee
      POSTGRES_PASSWORD: bee
      POSTGRES_DB: bee
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    container_name: koloda_app
    image: localhost/koloda_app:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8501:8501"
      - "8001:8001"
    volumes:
      - ./memento:/app/memento
      - ./storage:/app/storage
    env_file:
      - .env
    command: ["/app/podman/entrypoint.sh"]

volumes:
  pg_data: